services:
  pelacli:
    container_name: pelacli
    image: pelagosnetwork/pelacli:latest
    working_dir: /app
    volumes:
      - ./data:/data
      - ./pelacli.yaml:/config/pelacli.yaml
    ports:
      - "8081:8081"
    command:
      - consensus
      - --config=/config/pelacli.yaml

  appchain:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexa-arb-appchain
    working_dir: /app
    pid: "service:pelacli"
    image: appchain:latest
    volumes:
      - ./data:/data
      - ./config.yaml:/config/config.yaml
    ports:
      - "9090:9090"
      - "8080:8080"
    depends_on:
      - pelacli
    command:
      - -config=/config/config.yaml
    restart: unless-stopped

  explorer:
    image: pelagosnetwork/explorer:latest
    container_name: hexa-arb-explorer
    ports:
      - "3000:3000"
    environment:
      - RPC_URL=http://localhost:8080/rpc
      - EXTERNAL_RPC_URL=http://localhost:8081/rpc
    depends_on:
      - appchain
      - pelacli
